/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
var __export = (target, all) => {
  __markAsModule(target);
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __reExport = (target, module2, desc) => {
  if (module2 && typeof module2 === "object" || typeof module2 === "function") {
    for (let key of __getOwnPropNames(module2))
      if (!__hasOwnProp.call(target, key) && key !== "default")
        __defProp(target, key, { get: () => module2[key], enumerable: !(desc = __getOwnPropDesc(module2, key)) || desc.enumerable });
  }
  return target;
};
var __toModule = (module2) => {
  return __reExport(__markAsModule(__defProp(module2 != null ? __create(__getProtoOf(module2)) : {}, "default", module2 && module2.__esModule && "default" in module2 ? { get: () => module2.default, enumerable: true } : { value: module2, enumerable: true })), module2);
};
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    var fulfilled = (value) => {
      try {
        step(generator.next(value));
      } catch (e) {
        reject(e);
      }
    };
    var rejected = (value) => {
      try {
        step(generator.throw(value));
      } catch (e) {
        reject(e);
      }
    };
    var step = (x) => x.done ? resolve(x.value) : Promise.resolve(x.value).then(fulfilled, rejected);
    step((generator = generator.apply(__this, __arguments)).next());
  });
};

// main.ts
__export(exports, {
  default: () => ExecuteCodePlugin
});
var import_obsidian2 = __toModule(require("obsidian"));
var fs = __toModule(require("fs"));
var child_process = __toModule(require("child_process"));

// Outputter.ts
var Outputter = class {
  constructor(codeBlock) {
    this.codeBlockElement = codeBlock;
    this.stdoutText = "";
    this.stderrText = "";
  }
  clear() {
    if (this.outputElement) {
      this.stdoutElem.setText("");
      this.stderrElem.setText("");
    }
    this.stdoutText = "";
    this.stderrText = "";
  }
  delete() {
    if (this.outputElement)
      this.outputElement.style.display = "none";
    if (this.clearButton)
      this.clearButton.style.display = "none";
    this.clear();
  }
  write(text) {
    if (!this.outputElement) {
      this.addOutputElement();
    }
    if (!this.clearButton) {
      this.addClearButton();
    }
    this.stdoutText += text;
    if (!this.stderrText && !this.stdoutText)
      return;
    this.stdoutElem.setText(this.stdoutText);
    this.outputElement.style.display = "block";
    this.clearButton.style.display = "block";
  }
  writeErr(text) {
    if (!this.outputElement) {
      this.addOutputElement();
    }
    if (!this.clearButton) {
      this.addClearButton();
    }
    this.stderrText += text;
    if (!this.stderrText && !this.stdoutText)
      return;
    this.stderrElem.setText(this.stderrText);
    this.outputElement.style.display = "block";
    this.clearButton.style.display = "block";
  }
  getParentElement() {
    return this.codeBlockElement.parentElement;
  }
  addClearButton() {
    const parentEl = this.getParentElement();
    this.clearButton = document.createElement("button");
    this.clearButton.className = "clear-button";
    this.clearButton.setText("Clear");
    this.clearButton.addEventListener("click", () => this.delete());
    parentEl.appendChild(this.clearButton);
  }
  addOutputElement() {
    const parentEl = this.getParentElement();
    let hr = document.createElement("hr");
    this.outputElement = document.createElement("code");
    this.outputElement.classList.add("language-output");
    this.stdoutElem = document.createElement("span");
    this.stdoutElem.addClass("stdout");
    this.stderrElem = document.createElement("span");
    this.stderrElem.addClass("stderr");
    this.outputElement.appendChild(hr);
    this.outputElement.appendChild(this.stdoutElem);
    this.outputElement.appendChild(this.stderrElem);
    parentEl.appendChild(this.outputElement);
  }
};

// SettingsTab.ts
var import_obsidian = __toModule(require("obsidian"));
var SettingsTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Settings for the Code Execution Plugin." });
    new import_obsidian.Setting(containerEl).setName("Timeout (in seconds)").setDesc("The time after which a program gets shut down automatically. This is to prevent infinite loops. ").addText((slider) => slider.setValue("" + this.plugin.settings.timeout / 1e3).onChange((value) => __async(this, null, function* () {
      if (Number(value) * 1e3) {
        console.log("Timeout set to: " + value);
        this.plugin.settings.timeout = Number(value) * 1e3;
      }
      yield this.plugin.saveSettings();
    })));
    new import_obsidian.Setting(containerEl).setName("Node path").addText((text) => text.setValue(this.plugin.settings.nodePath).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.nodePath = value;
      console.log("Node path set to: " + value);
    })));
    new import_obsidian.Setting(containerEl).setName("Node arguments").addText((text) => text.setValue(this.plugin.settings.nodeArgs).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.nodeArgs = value;
      console.log("Node path set to: " + value);
    })));
    new import_obsidian.Setting(containerEl).setName("Python path").setDesc("The path to your Python installation.").addText((text) => text.setValue(this.plugin.settings.pythonPath).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.pythonPath = value;
      console.log("Python path set to: " + value);
    })));
    new import_obsidian.Setting(containerEl).setName("Python arguments").addText((text) => text.setValue(this.plugin.settings.pythonArgs).onChange((value) => __async(this, null, function* () {
      this.plugin.settings.pythonArgs = value;
      console.log("Node path set to: " + value);
    })));
  }
};

// main.ts
var supportedLanguages = ["js", "javascript", "python"];
var buttonText = "Run";
var runButtonClass = "run-code-button";
var runButtonDisabledClass = "run-button-disabled";
var hasButtonClass = "has-run-code-button";
var DEFAULT_SETTINGS = {
  timeout: 1e4,
  nodePath: "node",
  nodeArgs: "",
  pythonPath: "python",
  pythonArgs: ""
};
var ExecuteCodePlugin = class extends import_obsidian2.Plugin {
  onload() {
    return __async(this, null, function* () {
      yield this.loadSettings();
      this.addSettingTab(new SettingsTab(this.app, this));
      this.addRunButtons(document.body);
      this.registerMarkdownPostProcessor((element, _context) => {
        this.addRunButtons(element);
      });
    });
  }
  addRunButtons(element) {
    element.querySelectorAll("code").forEach((codeBlock) => {
      console.log("code block: " + codeBlock.tagName);
      const pre = codeBlock.parentElement;
      const parent = pre.parentElement;
      const language = codeBlock.className.toLowerCase();
      if (supportedLanguages.some((lang) => language.contains(`language-${lang}`)) && !parent.classList.contains(hasButtonClass)) {
        parent.classList.add(hasButtonClass);
        const button = this.createRunButton();
        pre.appendChild(button);
        const out = new Outputter(codeBlock);
        if (language.contains("language-js") || language.contains("language-javascript")) {
          button.addEventListener("click", () => {
            button.className = runButtonDisabledClass;
            this.runJavaScript(codeBlock.getText(), out, button);
          });
        } else if (language.contains("language-python")) {
          button.addEventListener("click", () => {
            button.className = runButtonDisabledClass;
            this.runPython(codeBlock.getText(), out, button);
          });
        }
      }
    });
  }
  createRunButton() {
    console.log("Add run button");
    const button = document.createElement("button");
    button.classList.add(runButtonClass);
    button.setText(buttonText);
    return button;
  }
  onunload() {
    document.querySelectorAll("pre > code").forEach((codeBlock) => {
      const pre = codeBlock.parentElement;
      const parent = pre.parentElement;
      if (parent.hasClass(hasButtonClass)) {
        parent.removeClass(hasButtonClass);
      }
    });
    document.querySelectorAll("." + runButtonClass).forEach((button) => button.remove());
    document.querySelectorAll("." + runButtonDisabledClass).forEach((button) => button.remove());
    document.querySelectorAll(".clear-button").forEach((button) => button.remove());
    document.querySelectorAll(".language-output").forEach((out) => out.remove());
    console.log("Unloaded plugin: Execute Code");
  }
  runJavaScript(codeBlockContent, outputter, button) {
    new import_obsidian2.Notice("Running...");
    const tempFileName = `temp_${Date.now()}.js`;
    console.log(tempFileName);
    fs.promises.writeFile(tempFileName, codeBlockContent).then(() => {
      console.log(`Execute ${this.settings.nodePath} ${tempFileName}`);
      const args = this.settings.nodeArgs ? this.settings.nodeArgs.split(" ") : [];
      args.push(tempFileName);
      const child = child_process.spawn(this.settings.nodePath, args);
      this.handleChildOutput(child, outputter, button, tempFileName);
    }).catch((err) => {
      console.log("Error in 'Obsidian Execute Code' Plugin while executing: " + err);
    });
  }
  runPython(codeBlockContent, outputter, button) {
    new import_obsidian2.Notice("Running...");
    const tempFileName = `temp_${Date.now()}.py`;
    fs.promises.writeFile(tempFileName, codeBlockContent).then(() => {
      const args = this.settings.pythonArgs ? this.settings.pythonArgs.split(" ") : [];
      args.push(tempFileName);
      const child = child_process.spawn("python", args);
      this.handleChildOutput(child, outputter, button, tempFileName);
    }).catch((err) => {
      console.log("Error in 'Obsidian Execute Code' Plugin while executing: " + err);
    });
  }
  loadSettings() {
    return __async(this, null, function* () {
      this.settings = Object.assign({}, DEFAULT_SETTINGS, yield this.loadData());
    });
  }
  saveSettings() {
    return __async(this, null, function* () {
      yield this.saveData(this.settings);
    });
  }
  handleChildOutput(child, outputter, button, fileName) {
    outputter.clear();
    child.stdout.on("data", (data) => {
      outputter.write(data.toString());
    });
    child.stderr.on("data", (data) => {
      outputter.writeErr(data.toString());
    });
    child.on("close", (code) => {
      button.className = runButtonClass;
      if (code === 0) {
        new import_obsidian2.Notice("Done!");
      } else {
        new import_obsidian2.Notice("Error!");
      }
      fs.promises.rm(fileName).catch((err) => {
        console.log("Error in 'Obsidian Execute Code' Plugin while removing file: " + err);
      });
    });
  }
};
